/**
 * Sitemap Index Generator
 *
 * Generates a sitemap index pointing to multiple sub-sitemaps.
 * This follows the same structure as the WordPress site:
 * - post-sitemap.xml (blog posts)
 * - page-sitemap.xml (static pages)
 * - product-sitemap.xml (products)
 * - category-sitemap.xml (blog categories)
 * - post_tag-sitemap.xml (blog tags)
 * - product_category-sitemap.xml (product categories)
 * - author-sitemap.xml (authors)
 *
 */

import type { MetadataRoute } from "next";
import { getSiteUrl } from "@/config/site";

export default function sitemap(): MetadataRoute.Sitemap {
	const baseUrl = getSiteUrl();

	// Return sitemap index entries pointing to sub-sitemaps
	// Each sub-sitemap is generated by its own route: /sitemap/[name]/route.ts
	return [
		{
			url: `${baseUrl}/sitemap/posts.xml`,
			lastModified: new Date(),
		},
		{
			url: `${baseUrl}/sitemap/pages.xml`,
			lastModified: new Date(),
		},
		{
			url: `${baseUrl}/sitemap/products.xml`,
			lastModified: new Date(),
		},
		{
			url: `${baseUrl}/sitemap/blog-categories.xml`,
			lastModified: new Date(),
		},
		{
			url: `${baseUrl}/sitemap/blog-tags.xml`,
			lastModified: new Date(),
		},
		{
			url: `${baseUrl}/sitemap/product-categories.xml`,
			lastModified: new Date(),
		},
		{
			url: `${baseUrl}/sitemap/authors.xml`,
			lastModified: new Date(),
		},
	];
}
